Sprint 1/step 1
Ren22/yandex-react-course pull request #1
Opened 2022-11-28 00:55 UTC by Ren22

2022-11-28 02:31 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

### **Работа отклонена.**

- Проект не запускается и не билдится.

  - не хватает зависимости `@ya.praktikum/react-developer-burger-ui-components`
  - есть ошибка связанная с ts в файле `components/order-list.tsx`.

  скриншот: https://yadi.sk/d/tybOUQZKDtnyQQ

### **Лучше сразу исправить и эти замечания:**

- Доделать табы по макету. (только помните, что не совсем табы в привычном понимании, контент у нас всегда один, он не должен переключаться, а вот скроллится может). https://yadi.sk/d/lvGKkgabLt16iw;

- По макету в компонентах `burger-ingredients` и `burger-constructor` не должно быть таких скроллов.

  - как у вас: https://yadi.sk/d/wcGJGMOvVMiY0g;

  - как в макете: https://yadi.sk/d/lciaEqww9-8bxw;

- в компоненте `burger-constructor` скроллится должен только контент, булки должны быть на месте.

  - как у вас: https://yadi.sk/d/fOXf8oFakrJ6tw;

  - как в макете: https://yadi.sk/d/wLjWvzZKflR6TA;

- По макету, в app-header должны быть ссылки, поправьте семантику, а также нужно чтобы была активна только первая ссылка. https://yadi.sk/d/5sGj-5c7vmUH_Q;

2022-11-28 16:36 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Декомпозиция файлов по директориям - практически соответствует описанию;
- Сборка и запуск проекта выполняются без ошибок;
- Используются функциональные компоненты;
- Используются css-modules, что тоже очень удобно и является хорошей практикой;

### **Но есть несколько замечаний, которые нужно исправить:**

- Нужно очистить проект от лишних файлов, которые остались при инициализации create-react-app. `App.test.tsx`.

- Нужно поправить цвет не активных ссылок:

  - как у вас: https://yadi.sk/d/ZHjfZUXibBlTSg;
  - как в макете: https://yadi.sk/d/BARe_TQLmfYICw;

- Увеличьте чуть чуть высоту компонентов: https://yadi.sk/d/ooKoWV__KcM8dQ;

- Булки должны быть одинаковыми: https://yadi.sk/d/G5AkHdkRUpX7PA;

- По макету булки должны иметь приписки `(верх)` и `(низ)`.

- По чек-листу у вас должен быть компонент burger-constructor. Вам нужно просто переименовать `order-list`.

### **Сделает код лучше:**

- при клике на таб плавно скролить список ингредиентов к нужному разделу

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders

- В некоторых местах нарушено форматирование кода, проблемы с отступами и в некоторых местах слишком длинные строки, что затрудняет чтение кода. Об оформлении кода можно почитать здесь https://learn.javascript.ru/coding-style. Постарайтесь использовать автоматическое форматирование, это сильно экономит время. Одно из наиболее популярных дополнений для форматирования кода - Prettier (https://prettier.io/)

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2022-11-28 16:36 UTC, ArslanMustafin commented on src/components/burger-ingredients/burger-ingredients.tsx
> +  );
**Надо исправить:**

Лучше делайте фильтр по типу) а не по названиям.

```js
ingredients.filter((item) => item.type === "bun")
ingredients.filter((item) => item.type === "main")
ingredients.filter((item) => item.type === "sauce")
```

2022-11-28 16:36 UTC, ArslanMustafin commented on src/components/burger-ingredients/burger-ingredients.tsx
> +  const [current, setCurrent] = useState("Breads");
**Можно лучше:**

Используйте lowerCase, для значений.

2022-11-28 16:36 UTC, ArslanMustafin commented on src/components/header/header.tsx
> +  const [current] = useState("constructor");
**Надо исправить:**

Если вы не меняете собираетесь менять стейт, то используйте обычную переменную.

2022-11-28 16:36 UTC, ArslanMustafin commented on src/components/order-list/order-list.tsx
> +  const ordersSum = burgersData.reduce((p, n) => p + n.price, 0);
**Можно лучше:**

Цена считается не правильно.
Надо помнить что булки у нас 2 штуки, и они одинаковые. Лучше всего считать после того, как вы отфильтруете ингредиенты и булки.
а также лучше использовать useMemo.

2022-11-28 16:36 UTC, ArslanDev666 commented on src/components/order-list/order-list.tsx
> +        {burgersData.slice(1, burgersData.length - 1).map((b, i) => (
**Можно лучше:**

Используйте фильтрацию до рендера.

```js
const ingredients = data.filter((ingredient) => ingredient.type !== 'bun');
```

2022-11-28 16:36 UTC, ArslanDev666 commented on src/components/order-list/order-list.tsx
> +  const bottomBread = breads.pop();
**Можно лучше:**

Используйте find для нахождения булки))

```js
const bun = data.find((ingredient) => ingredient.type === 'bun');
```

2022-12-04 01:07 UTC, Ren22 commented
@ArslanDev666 `Но есть несколько замечаний, которые нужно исправить` поправил, более мелкие замечания учту во втором реквесте(он уже готов :))

2022-12-04 17:03 UTC, Ren22 commented on src/components/burger-ingredients/burger-ingredients.tsx
> +  );
resolved in step 2

2022-12-04 17:06 UTC, Ren22 commented on src/components/header/header.tsx
> +  const [current] = useState("constructor");
Пока не использую, думаю будет нужно дальеш

2022-12-04 17:06 UTC, Ren22 commented on src/components/order-list/order-list.tsx
> +  const ordersSum = burgersData.reduce((p, n) => p + n.price, 0);
fixed in step2

2022-12-04 17:07 UTC, Ren22 commented on src/components/order-list/order-list.tsx
> +        {burgersData.slice(1, burgersData.length - 1).map((b, i) => (
fixed in step 2

2022-12-04 17:07 UTC, Ren22 commented on src/components/order-list/order-list.tsx
> +  const bottomBread = breads.pop();
fixed in step 2

2022-12-05 11:34 UTC, merged