Sprint 1/step 2
Ren22/yandex-react-course pull request #2
Opened 2022-12-04 01:04 UTC by Ren22

2022-12-04 05:43 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Теперь ингредиенты приходят от сервера;

- В приложении есть модальные окна;

### **Но есть несколько замечаний, которые нужно исправить:**

- по основному функционалу замечаний нет, но есть замечания связанные с логикой работы приложения в некоторых местах, отметил в коде.
### **Сделает код лучше:**

- при клике на таб скролить список ингредиентов к нужному разделу.

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

2022-12-04 05:43 UTC, ArslanDev666 commented on src/api/burgers.tsx
> +}
**Можно лучше:**

не очень понимаю, зачем вам это.

2022-12-04 05:43 UTC, ArslanDev666 commented on src/components/burger-ingredients-item/burger-ingredients-item.tsx
> +export interface IngredientDetailsType {
**Можно лучше:**

Вынесите тип в папку `utils`, в файл `types.ts`.

2022-12-04 05:43 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.tsx
> +  const { burgersData } = props;
**Можно лучше:**

Почему бы сразу не деструктурировать пропс выше.

2022-12-04 05:43 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.tsx
>    );
**Надо исправить:**

Используйте фильтрацию по типу, а не по имени, у вас 3 разных типа ингредиента.

А также используйте `useMemo`, чтобы фильтрация не выполнялась каждый ререндер.

2022-12-04 05:43 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.tsx
> +            <BurgerIngredientsItem key={key} ingredientDetails={b} />
**Можно лучше:**

Здесь и далее.

Используйте тут id ингредиента, а не индекс массива.
Подробнее почему это плохо: https://stackoverflow.com/questions/46735483/error-do-not-use-array-index-in-keys

2022-12-04 05:43 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.tsx
> +  const { burgersData } = props;
**Можно лучше:**

аналогичное замечание в burger-ingredients.

2022-12-04 05:43 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.tsx
>    const ordersSum = burgersData.reduce((p, n) => p + n.price, 0);
**Надо исправить:**

вы не учитываете, что булок у нас 2 шт, и булка должна быть одна в массиве.

т.е. мы сначала делаем фильтрацию ингредиентов от булок, после этого достаем какую-нибудь булку, и только тогда считаем цену.

```js
const totalPrice = useMemo(() => {
  return (bun.price * 2) + ingredients.reduce((p, n) => p + n.price, 0)
}, [bun, ingredients])
```

2022-12-04 05:43 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.tsx
>    const bread = burgersData.filter((it) => it.name.includes("булка"))[0];
**Надо исправить:**

Аналогичное замечание в burger-ingredients.

2022-12-04 05:43 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.tsx
> +  const modal = (
**Можно лучше:**

не стоит это выносить в отдельную переменную)

2022-12-04 05:43 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.tsx
>          {burgersData.slice(1, burgersData.length - 1).map((b, i) => (
**Можно лучше:**

Slice лучше делать до jsx, например после фильтрации)

2022-12-04 05:43 UTC, ArslanDev666 commented on src/components/burger-ingredients-item/burger-ingredients-item.tsx
> +  const { image, name, price } = props.ingredientDetails;
**Можно лучше:**

Почему бы сразу не деструктурировать пропс выше.

2022-12-04 05:43 UTC, ArslanDev666 commented on src/components/burger-ingredients-item/burger-ingredients-item.tsx
> +  const modal = (
**Можно лучше:**

Как и в другом компоненте, тут модальное окно не стоит выносить в отдельную переменную.

2022-12-04 05:43 UTC, ArslanDev666 commented on src/components/ingredient-details/ingredient-details.tsx
> +        style={{ gap: "20px" }}
**Надо исправить:**

Старайтесь не использовать инлайн стили, лучше создайте дополнительный класс и используйте его.

2022-12-04 05:43 UTC, ArslanDev666 commented on src/components/modal/modal.tsx
> +    window.addEventListener("keydown", closeModal);
**Можно лучше:**

Лучше поставить событие на document.

Грубо говоря: window - окно браузера, document - это содержимое всего сайта.

2022-12-04 05:43 UTC, ArslanDev666 commented on src/components/modal/modal.tsx
> +            {header}
**Можно лучше:**

Возможно стоит занести header под условие ниже))

2022-12-04 15:24 UTC, Ren22 commented on src/api/burgers.tsx
> +}
Останок от предыдущего кода, удалю :)

2022-12-04 15:24 UTC, Ren22 commented on src/components/modal/modal.tsx
> +    window.addEventListener("keydown", closeModal);
Почему это именно лучше?

2022-12-04 15:24 UTC, Ren22 commented on src/components/burger-ingredients-item/burger-ingredients-item.tsx
> +  const { image, name, price } = props.ingredientDetails;
как именно это можно сделать?

2022-12-05 02:18 UTC, ArslanMustafin commented on src/components/burger-ingredients-item/burger-ingredients-item.tsx
> +  const { image, name, price } = props.ingredientDetails;
```js
const BurgerIngredientsItem = ({ingredientDetails: {image, name, price}}: Props) => {
```

2022-12-05 02:23 UTC, ArslanDev666 commented on src/components/modal/modal.tsx
> +    window.addEventListener("keydown", closeModal);
Вот тут красиво написано, почему лучше) 
https://stackoverflow.com/a/12045503

2022-12-05 02:41 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

### **Вы молодец!🔥 Работа принята, удачи в дальнейшем обучении.**

- Все замечания с прошлого ревью были исправлены.

### **Сделает код лучше:**

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders

2022-12-05 11:34 UTC, merged